project:
  title: "Maciej Beręsewicz"
  output-dir: ./docs/
website:
  navbar:
    background: primary
    right:
      - href: ../pl
        text: Polish
      - href: ../
        text: English
    left:
      - href: news.qmd
        text: News
      - href: index.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: index.qmd
        text: Projects
      - sidebar:teaching
      - href: index.qmd
        text: Software
      - href: activities.qmd
        text: Activities
      - href: contact.qmd
        text: Contact
  sidebar:
      - id: teaching
        title: "Teaching"
        style: "docked"
        background: light
        collapse-level: 1
        contents:
          - href: ./teaching/classes.qmd
          - href: ./teaching/materials.qmd
          - href: ./teaching/seminars.qmd
          - href: ./teaching/students.qmd

lang: en

format:
  html:
    theme:
     light: flatly
     dark: flatly
    css: styles.css
    toc: true
