project:
  type: website

website:
  title: "Maciej Beręsewicz"
  open-graph:
    locale: en-GB
    site-name: "Maciej Beręsewicz"

profile:
  default: english
  group: [english, polish]

comments:
  giscus:
    repo: berenz/berenz.github.io

